name: Test, Lint and Deploy script
on:
    push:
        branches:
            - main

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Lint code
              run: npm run lint
            - name: Run tests
              run: npm test

    Build:
        needs: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Build code
              run: npm run build
            - name: upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dist-files
                path: dist
                

    Fake-Deploy:
      needs: Build
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            name: dist-files
            path: dist
        - name: List files
          run: ls 
        - name: Deploy
          run: echo "Fake deployed.."
