name: Test, Lint and Deploy script
on:
    push:
        branches:
            - main

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install depepdencies
              run: npm ci

            - name: Lint code
              run: npm run lint

            - name: Run tests
              run: npm test

            - name: Fake deploy
              run: echo "fake deploy initiated... \n Fake deployed successfully"
            

